server:
  port: 8080

spring:
  # application
  application:
    name: support-svc
  # datasource
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    maximum-pool-size: 100
    minimum-idle: 1
    idle-timeout: 300000
    max-lifetime: 1800000
    connection-timeout: 3000
    pool-name: HikariCPPool
  # h2 console
  h2:
    console:
      enabled: true
      path: /h2/console
  # jpa
  jpa:
    hibernate:
        ddl-auto: create
# logging
logging:
  level:
    root: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n'

meowu:
  web:
    cors:
      enabled: true
    request-log:
      enabled: true
    converter: gson