package com.meowu.svc.support.commons.constant;

public interface AuditLogConstant{

    String MODULE_SYS_MESSAGE = "SYS_MESSAGE";
    String MODULE_GENERAL_CODE = "GENERAL_CODE";
    String MODULE_APPLICATION = "APPLICATION";
    String MODULE_APPLICATION_VERSION = "APPLICATION_VERSION";
    String MODULE_APPLICATION_LOG = "APPLICATION_LOG";
    String MODULE_APPLICATION_LOG_ITEM = "APPLICATION_LOG_ITEM";

    String FUNCTION_CREATE = "CREATE";
    String FUNCTION_UPDATE = "UPDATE";
    String FUNCTION_DELETE = "DELETE";
}
